/**
 * Created by andy on 12/8/16.
 */
public class NLPConsts {
    public static final String article = "The FIFA World Cup, often simply called the World Cup, is an international association football competition contested by the senior men's national teams of the members of Fédération Internationale de Football Association (FIFA), the sport's global governing body. The championship has been awarded every four years since the inaugural tournament in 1930, except in 1942 and 1946 when it was not held because of the Second World War. The current champion is Germany, which won its fourth title at the 2014 tournament in Brazil.\n" +
            "\n" +
            "The current format of the competition involves a qualification phase, which currently takes place over the preceding three years, to determine which teams qualify for the tournament phase, which is often called the World Cup Finals. 32 teams, including the automatically qualifying host nation(s), compete in the tournament phase for the title at venues within the host nation(s) over a period of about a month.\n" +
            "\n" +
            "The 20 World Cup tournaments have been won by eight different national teams. Brazil have won five times, and they are the only team to have played in every tournament. The other World Cup winners are Germany and Italy, with four titles each; Argentina and inaugural winner Uruguay, with two titles each; and England, France and Spain, with one title each.\n" +
            "\n" +
            "The World Cup is the most prestigious association football tournament in the world as well as the most widely viewed and followed sporting event in the world, exceeding even the Olympic Games; the cumulative audience of all matches of the 2006 FIFA World Cup was estimated to be 26.29 billion with an estimated 715.1 million people watching the final match, a ninth of the entire population of the planet.[1][2][3][4]" +
            "Previous international competitions\n" +
            "\n" +
            "The world's first international football match was a challenge match played in Glasgow in 1872 between Scotland and England,[5] which ended in a 0–0 draw. The first international tournament, the inaugural edition of the British Home Championship, took place in 1884.[6] As football grew in popularity in other parts of the world at the turn of the 20th century, it was held as a demonstration sport with no medals awarded at the 1900 and 1904 Summer Olympics (however, the IOC has retroactively upgraded their status to official events), and at the 1906 Intercalated Games.[7]\n" +
            "\n" +
            "After FIFA was founded in 1904, it tried to arrange an international football tournament between nations outside the Olympic framework in Switzerland in 1906. These were very early days for international football, and the official history of FIFA describes the competition as having been a failure.[8]\n" +
            "\n" +
            "At the 1908 Summer Olympics in London, football became an official competition. Planned by The Football Association (FA), England's football governing body, the event was for amateur players only and was regarded suspiciously as a show rather than a competition. Great Britain (represented by the England national amateur football team) won the gold medals. They repeated the feat in 1912 in Stockholm.\n" +
            "\n" +
            "With the Olympic event continuing to be contested only between amateur teams, Sir Thomas Lipton organised the Sir Thomas Lipton Trophy tournament in Turin in 1909. The Lipton tournament was a championship between individual clubs (not national teams) from different nations, each one of which represented an entire nation. The competition is sometimes described as The First World Cup,[9] and featured the most prestigious professional club sides from Italy, Germany and Switzerland, but the FA of England refused to be associated with the competition and declined the offer to send a professional team. Lipton invited West Auckland, an amateur side from County Durham, to represent England instead. West Auckland won the tournament and returned in 1911 to successfully defend their title.\n" +
            "\n" +
            "In 1914, FIFA agreed to recognise the Olympic tournament as a \"world football championship for amateurs\", and took responsibility for managing the event.[10] This paved the way for the world's first intercontinental football competition, at the 1920 Summer Olympics, contested by Egypt and 13 European teams, and won by Belgium.[11] Uruguay won the next two Olympic football tournaments in 1924 and 1928. Those were also the first two open world championships, as 1924 was the start of FIFA's professional era.\n" +
            "World Cups before World War II\n" +
            "Estadio Centenario, the location of the first World Cup final in 1930 in Montevideo, Uruguay\n" +
            "\n" +
            "Due to the success of the Olympic football tournaments, FIFA, with President Jules Rimet as the driving force, again started looking at staging its own international tournament outside of the Olympics. On 28 May 1928, the FIFA Congress in Amsterdam decided to stage a world championship itself.[12] With Uruguay now two-time official football world champions and to celebrate their centenary of independence in 1930, FIFA named Uruguay as the host country of the inaugural World Cup tournament.\n" +
            "\n" +
            "The national associations of selected nations were invited to send a team, but the choice of Uruguay as a venue for the competition meant a long and costly trip across the Atlantic Ocean for European sides. Indeed, no European country pledged to send a team until two months before the start of the competition. Rimet eventually persuaded teams from Belgium, France, Romania, and Yugoslavia to make the trip. In total, 13 nations took part: seven from South America, four from Europe and two from North America.\n" +
            "\n" +
            "The first two World Cup matches took place simultaneously on 13 July 1930, and were won by France and the USA, who defeated Mexico 4–1 and Belgium 3–0 respectively. The first goal in World Cup history was scored by Lucien Laurent of France.[13] In the final, Uruguay defeated Argentina 4–2 in front of a crowd of 93,000 people in Montevideo, and in doing so became the first nation to win the World Cup.[14]\n" +
            "\n" +
            "After the creation of the World Cup, the 1932 Summer Olympics, held in Los Angeles, did not plan to include football as part of the schedule due to the low popularity of the sport in the United States, as American football had been growing in popularity. FIFA and the IOC also disagreed over the status of amateur players, and so football was dropped from the Games.[15] Olympic football returned at the 1936 Summer Olympics, but was now overshadowed by the more prestigious World Cup.\n" +
            "\n" +
            "The issues facing the early World Cup tournaments were the difficulties of intercontinental travel, and war. Few South American teams were willing to travel to Europe for the 1934 and 1938 tournaments, with Brazil the only South American team to compete in both. The 1942 and 1946 competitions, which Nazi Germany and Brazil sought to host,[16] were cancelled due to World War II and its aftermath.\n" +
            "World Cups after World War II\n" +
            "\n" +
            "The 1950 World Cup, held in Brazil, was the first to include British participants. British teams withdrew from FIFA in 1920, partly out of unwillingness to play against the countries they had been at war with, and partly as a protest against foreign influence on football,[17] but rejoined in 1946 following FIFA's invitation.[18] The tournament also saw the return of 1930 champions Uruguay, who had boycotted the previous two World Cups. Uruguay won the tournament again after defeating the host nation Brazil, in the match called \"Maracanazo\" (Portuguese: Maracanaço)." +
            "In the tournaments between 1934 and 1978, 16 teams competed in each tournament, except in 1938, when Austria was absorbed into Germany after qualifying, leaving the tournament with 15 teams, and in 1950, when India, Scotland, and Turkey withdrew, leaving the tournament with 13 teams.[19] Most of the participating nations were from Europe and South America, with a small minority from North America, Africa, Asia, and Oceania. These teams were usually defeated easily by the European and South American teams. Until 1982, the only teams from outside Europe and South America to advance out of the first round were: USA, semi-finalists in 1930; Cuba, quarter-finalists in 1938; North Korea, quarter-finalists in 1966; and Mexico, quarter-finalists in 1970.\n" +
            "Expansion to 32 teams\n" +
            "\n" +
            "The tournament was expanded to 24 teams in 1982,[20] and then to 32 in 1998,[21] also allowing more teams from Africa, Asia and North America to take part. Since then, teams from these regions have enjoyed more success, with several having reached the quarter-finals: Mexico, quarter-finalists in 1986; Cameroon, quarter-finalists in 1990; South Korea, finishing in fourth place in 2002; Senegal, along with USA, both quarter-finalists in 2002; Ghana, quarter-finalists in 2010; and Costa Rica, quarter-finalists in 2014. Nevertheless, European and South American teams continue to dominate, e.g., the quarter-finalists in 1994, 1998, and 2006 were all from Europe or South America and so were the finalists of all tournaments so far.\n" +
            "\n" +
            "Two hundred teams entered the 2002 FIFA World Cup qualification rounds; 198 nations attempted to qualify for the 2006 FIFA World Cup, while a record 204 countries entered qualification for the 2010 FIFA World Cup.[22]\n" +
            "Possible expansion to 40 teams\n" +
            "\n" +
            "In October 2013, Sepp Blatter spoke of guaranteeing the Caribbean Football Union's region a position in the World Cup.[23] In the 25 October 2013 edition of the FIFA Weekly Blatter wrote that: \"From a purely sporting perspective, I would like to see globalisation finally taken seriously, and the African and Asian national associations accorded the status they deserve at the FIFA World Cup. It cannot be that the European and South American confederations lay claim to the majority of the berths at the World Cup.\"[24] Those two remarks suggested to commentators that Blatter could be putting himself forward for re-election to the FIFA Presidency.[25]\n" +
            "\n" +
            "Following the magazine's publication, Blatter's would-be opponent for the FIFA Presidency, UEFA President Michel Platini responded that he intended to extend the World Cup to 40 national associations, increasing the number of participants by eight. Platini said that he would allocate an additional berth to UEFA, two to Asia Football Confederation and Confederation of African Football, two shared between CONCACAF and CONMEBOL, and a guaranteed place for the Oceania Football Confederation.[26] Platini was clear about why he wanted to expand the World Cup. He said: \"[The World Cup is] not based on the quality of the teams because you don't have the best 32 at the World Cup ... but it's a good compromise. ... It's a political matter so why not have more Africans? The competition is to bring all the people of all the world. If you don't give the possibility to participate, they don't improve.\"[26]\n" +
            "\n" +
            "In October 2016 FIFA president Gianni Infantino stated his support for a 48-team World Cup in 2026.[27]\n" +
            "2015 FIFA corruption case\n" +
            "Main article: 2015 FIFA corruption case\n" +
            "\n" +
            "By May 2015, the games were under a particularly dark cloud because of the 2015 FIFA corruption case, allegations and criminal charges of bribery, fraud and money laundering to corrupt the issuing of media and marketing rights (rigged bids) for FIFA games,[28] with FIFA officials accused of taking bribes totaling more than $150 million over 24 years. In late May, the U.S. Justice Department announced a 47-count indictment with charges of racketeering, wire fraud and money laundering conspiracy against 14 people. Arrests of over a dozen FIFA officials were made since that time, particularly on May 29 and December 3.[29]\n" +
            "\n" +
            "By the end of May 2015, a total of nine FIFA officials and five executives of sports and broadcasting markets had already been charged on corruption. At the time, FIFA president Sepp Blatter announced he would relinquish his position in February 2016.[30]\n" +
            "\n" +
            "On 4 June 2015 Chuck Blazer while co-operating with the FBI and the Swiss authorities admitted that he and the other members of FIFA's executive committee were bribed in order to promote the 1998 and 2010 World Cups.[31]\n" +
            "\n" +
            "On 10 June 2015 Swiss authorities seized computer data from the offices of Sepp Blatter.[32]\n" +
            "Also, on 10 June 2015 FIFA postponed the bidding process for the 2026 FIFA World Cup in light of the allegations surrounding bribery in the awarding of the 2018 and 2022 tournaments. Then-secretary general Jérôme Valcke stated, \"Due to the situation, I think it's nonsense to start any bidding process for the time being.\"[33]\n" +
            "\n" +
            "On 28 October 2015, Blatter and FIFA VP Michel Platini, a potential candidate for presidency, were suspended for 90 days; both maintained their innocence in statements made to the news media.[34]\n" +
            "\n" +
            "On 3 December 2015 two FIFA vice-presidents were arrested on suspicion of bribery in the same Zurich hotel where seven FIFA officials had been arrested in May.[35] An additional 16 indictments by the U.S. Department of Justice were announced on the same day.[36]\n" +
            "Other FIFA tournaments\n" +
            "\n" +
            "An equivalent tournament for women's football, the FIFA Women's World Cup, was first held in 1991 in China.[37] The women's tournament is smaller in scale and profile than the men's, but is growing; the number of entrants for the 2007 tournament was 120, more than double that of 1991.\n" +
            "\n" +
            "Football has been included in every Summer Olympic Games except 1896 and 1932. Unlike many other sports, the men's football tournament at the Olympics is not a top-level tournament, and since 1992, an under-23 tournament with each team allowed three over-age players.[38] Women's football made its Olympic debut in 1996, and is contested between full national sides with no age restrictions.\n" +
            "\n" +
            "The FIFA Confederations Cup is a tournament held one year before the World Cup at the World Cup host nation(s) as a dress rehearsal for the upcoming World Cup. It is contested by the winners of each of the six FIFA confederation championships, along with the FIFA World Cup champion and the host country.[39]\n" +
            "\n" +
            "FIFA also organises international tournaments for youth football (FIFA U-20 World Cup, FIFA U-17 World Cup, FIFA U-20 Women's World Cup, FIFA U-17 Women's World Cup), club football (FIFA Club World Cup), and football variants such as futsal (FIFA Futsal World Cup) and beach soccer (FIFA Beach Soccer World Cup). The latter three do not have a women's version, although a FIFA Women's Club World Cup is planned for 2017.\n" +
            "\n" +
            "When the U-20 Women's World Cup is held the year before the Women's World Cup, both tournaments are awarded in a single bidding process. The U-20 tournament serves as a dress rehearsal for the larger competition, the same role as the Confederations Cup plays in the men's game.\n" +
            "Trophy\n" +
            "Main article: FIFA World Cup Trophy\n" +
            "\n" +
            "From 1930 to 1970, the Jules Rimet Trophy was awarded to the World Cup winning team. It was originally simply known as the World Cup or Coupe du Monde, but in 1946 it was renamed after the FIFA president Jules Rimet who set up the first tournament. In 1970, Brazil's third victory in the tournament entitled them to keep the trophy permanently. However, the trophy was stolen in 1983 and has never been recovered, apparently melted down by the thieves.[40]\n" +
            "\n" +
            "After 1970, a new trophy, known as the FIFA World Cup Trophy, was designed. The experts of FIFA, coming from seven countries, evaluated the 53 presented models, finally opting for the work of the Italian designer Silvio Gazzaniga. The new trophy is 36 cm (14.2 in) high, made of solid 18 carat (75%) gold and weighs 6.175 kg (13.6 lb). The base contains two layers of semi-precious malachite while the bottom side of the trophy bears the engraved year and name of each FIFA World Cup winner since 1974. The description of the trophy by Gazzaniga was: \"The lines spring out from the base, rising in spirals, stretching out to receive the world. From the remarkable dynamic tensions of the compact body of the sculpture rise the figures of two athletes at the stirring moment of victory.\"[41]\n" +
            "\n" +
            "This new trophy is not awarded to the winning nation permanently. World Cup winners retain the trophy only until the post-match celebration is finished. They are awarded a gold-plated replica rather than the solid gold original immediately afterwards.[42]\n" +
            "\n" +
            "Currently, all members (players, coaches, and managers) of the top three teams receive medals with an insignia of the World Cup Trophy; winners' (gold), runners-up' (silver), and third-place (bronze). In the 2002 edition, fourth-place medals were awarded to hosts South Korea. Before the 1978 tournament, medals were only awarded to the eleven players on the pitch at the end of the final and the third-place match. In November 2007, FIFA announced that all members of World Cup-winning squads between 1930 and 1974 were to be retroactively awarded winners' medals.[43][44][45]\n" +
            "Format\n" +
            "Qualification\n" +
            "Main article: FIFA World Cup qualification\n" +
            "\n" +
            "Since the second World Cup in 1934, qualifying tournaments have been held to thin the field for the final tournament.[46] They are held within the six FIFA continental zones (Africa, Asia, North and Central America and Caribbean, South America, Oceania, and Europe), overseen by their respective confederations. For each tournament, FIFA decides the number of places awarded to each of the continental zones beforehand, generally based on the relative strength of the confederations' teams.\n" +
            "\n" +
            "The qualification process can start as early as almost three years before the final tournament and last over a two-year period. The formats of the qualification tournaments differ between confederations. Usually, one or two places are awarded to winners of intercontinental play-offs. For example, the winner of the Oceanian zone and the fifth-placed team from the Asian zone entered a play-off for a spot in the 2010 World Cup.[47] From the 1938 World Cup onwards, host nations receive automatic qualification to the final tournament. This right was also granted to the defending champions between 1938 and 2002, but was withdrawn from the 2006 FIFA World Cup onward, requiring the champions to qualify. Brazil, winners in 2002, were the first defending champions to play qualifying matches.[48]\n" +
            "Final tournament\n" +
            "For the various formats used in previous tournaments, see History of the FIFA World Cup § Format of each final tournament.\n" +
            "\n" +
            "The current final tournament has been used since 1998 and features 32 national teams competing over the course of a month in the host nation(s). There are two stages: the group stage followed by the knockout stage.[49]\n" +
            "\n" +
            "In the group stage, teams compete within eight groups of four teams each. Eight teams are seeded, including the hosts, with the other seeded teams selected using a formula based on the FIFA World Rankings and/or performances in recent World Cups, and drawn to separate groups.[50] The other teams are assigned to different \"pots\", usually based on geographical criteria, and teams in each pot are drawn at random to the eight groups. Since 1998, constraints have been applied to the draw to ensure that no group contains more than two European teams or more than one team from any other confederation.[51]\n" +
            "\n" +
            "Each group plays a round-robin tournament, in which each team is scheduled for three matches against other teams in the same group. This means that a total of six matches are played within a group. The last round of matches of each group is scheduled at the same time to preserve fairness among all four teams.[52] The top two teams from each group advance to the knockout stage. Points are used to rank the teams within a group. Since 1994, three points have been awarded for a win, one for a draw and none for a loss (before, winners received two points).\n" +
            "\n" +
            "If one considers all possible outcomes (win, draw, loss) for all six matches in a group, there are 729 (= 36) different outcome combinations possible. However a certain number (207) of these combinations lead to ties between the second and third places. In such case, the ranking among these teams is determined as follows:[53]\n" +
            "\n" +
            "    Greatest combined goal difference in all group matches\n" +
            "    Greatest combined number of goals scored in all group matches\n" +
            "    If more than one team remain level after applying the above criteria, their ranking will be determined as follows:\n" +
            "        Greatest number of points in head-to-head matches among those teams\n" +
            "        Greatest goal difference in head-to-head matches among those teams\n" +
            "        Greatest number of goals scored in head-to-head matches among those teams\n" +
            "    If any of the teams above remain level after applying the above criteria, their ranking will be determined by the drawing of lots\n" +
            "\n" +
            "The knockout stage is a single-elimination tournament in which teams play each other in one-off matches, with extra time and penalty shootouts used to decide the winner if necessary. It begins with the round of 16 (or the second round) in which the winner of each group plays against the runner-up of another group. This is followed by the quarter-finals, the semi-finals, the third-place match (contested by the losing semi-finalists), and the final.[49]" +
            "Two players share the record for playing in the most World Cups; Mexico's Antonio Carbajal (1950–1966) and Germany's Lothar Matthäus (1982–1998) both played in five tournaments.[77] Matthäus has played the most World Cup matches overall, with 25 appearances.[78] Brazil's Djalma Santos (1954–1962), West Germany's Franz Beckenbauer (1966–1974) and Germany's Philipp Lahm (2006–2014) are the only players to be named to three Finals All-Star Teams.[79]\n" +
            "\n" +
            "Miroslav Klose of Germany (2002–2014) is the all-time top scorer at the finals, with 16 goals. He broke Ronaldo of Brazil's record of 15 goals (1998–2006) during 2014 semi-final match against Brazil. West Germany's Gerd Müller (1970–1974) is third, with 14 goals.[80] The fourth placed goalscorer, France's Just Fontaine, holds the record for the most goals scored in a single World Cup; all his 13 goals were scored in the 1958 tournament.[81]\n" +
            "\n" +
            "In November 2007, FIFA announced that all members of World Cup-winning squads between 1930 and 1974 were to be retroactively awarded winners' medals.[43] This made Brazil's Pelé the only player to have won three World Cup winners' medals (1958, 1962, and 1970, although he did not play in the 1962 final due to injury),[82] with 20 other players who have won two winners' medals. Seven players have collected all three types of World Cup medals (winners', runner- ups', and third-place); five players were from West Germany's squad of 1966–1974 including Franz Beckenbauer, Jürgen Grabowski, Horst-Dieter Höttges, Sepp Maier and Wolfgang Overath (1966–1974), Italy's Franco Baresi (1982, 1990, 1994) and the most recent has been Miroslav Klose of Germany (2002–2014) with four consecutive medals.\n" +
            "\n" +
            "Brazil's Mário Zagallo and West Germany's Franz Beckenbauer are the only people to date to win the World Cup as both player and head coach. Zagallo won in 1958 and 1962 as a player and in 1970 as head coach.[83] Beckenbauer won in 1974 as captain and in 1990 as head coach.[84] Italy's Vittorio Pozzo is the only head coach to ever win two World Cups (1934 and 1938).[85] All World Cup winning head coaches were natives of the country they coached to victory.\n" +
            "\n" +
            "Among the national teams, Germany has played the most World Cup matches (106) and appeared in the most finals (8), semi-finals (13), quarter-finals (16) as well as scoring the most World Cup goals (224), while Brazil has appeared in the most World Cups (20).[86] The two teams have played each other twice in the World Cup, in the 2002 final and in the 2014 semi-final.";
}
