FROM tomcat:7.0-jre8
MAINTAINER "Ainuddin Faizan <andyfaizan@gmail.com>"

ADD settings.xml /usr/local/tomcat/conf/
ADD tomcat-users.xml /usr/local/tomcat/conf/
ADD context.xml /usr/local/tomcat/conf/
ADD wordnet /usr/local/tomcat/wordnet/